"""
Generate savetest.c.

The saved game format lives in geochess.h and geochess.c, which cannot
be compiled on the host: they include <geos.h> and declare the menu
resources as `const void`, which only cc65 accepts.

Rather than keep a second copy of the pack, validate and unpack code
here, where it could silently drift from the real thing, this pulls
those functions straight out of the sources and wraps them in a host
harness. What gets tested is what ships.

Usage:  python3 mksavetest.py [output.c]
"""

import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, os.pardir, "src")


def read(name):
    with io.open(os.path.join(SRC, name), encoding="utf-8") as f:
        return f.read().replace("\r\n", "\n")


def span(text, start_marker, end_marker, what):
    a = text.find(start_marker)
    if a < 0:
        sys.exit("mksavetest: cannot find the start of %s" % what)
    b = text.find(end_marker, a)
    if b < 0:
        sys.exit("mksavetest: cannot find the end of %s" % what)
    return text[a:b]


HEADER = read("geochess.h")
BODY = read("geochess.c")

# the record definition and its constants, verbatim from geochess.h
record = span(HEADER, "#define SAVE_MAGIC0", "} SaveGame;", "the SaveGame record")
record += "} SaveGame;\n"

# the pack / validate / unpack code, verbatim from geochess.c
logic = span(BODY, "#define SAVE_PACK(sq)", "void LoadGameMenuHandler",
             "the save/restore functions")

harness = r'''/*
 * Generated by mksavetest.py. Do not edit; edit the sources instead.
 *
 * Round trips the saved game format and checks that the validator
 * rejects damaged records before any of it reaches the engine.
 */
#include <stdio.h>
#include <string.h>
#include "geochess-ai.h"

#define NOTATION_ROWS 11
#define WHT 0
#define BLK 1
#define EMPTY 0

static unsigned char notation_row_count = 0;
static char notation_moves[NOTATION_ROWS][5];
static unsigned char notation_players[NOTATION_ROWS];

''' + record + "\n" + logic + r'''

/* ------------------------------------------------------------------ */

static int fails = 0;

static void chk(const char *n, int got, int want)
{
    printf("  %-52s %s\n", n, got == want ? "OK" : "*** FAIL ***");
    if (got != want) { fails++; printf("      got %d want %d\n", got, want); }
}

static SaveGame rec;
static unsigned char board_snap[128];

static int play(const char *from, const char *to)
{
    ChessMove m;
    m.from = ((8 - (from[1] - '0')) * 16) + (from[0] - 'a');
    m.to = ((8 - (to[1] - '0')) * 16) + (to[0] - 'a');
    ChessFormatMove(&m, user_move);
    return playerMove();
}

int main(void)
{
    int i, side_before, rights_before, ep_before, state_before;

    printf("Save record:\n");
    printf("  sizeof(SaveGame) = %d bytes\n", (int)sizeof(SaveGame));

    /* --- round trip of the opening position --------------------- */
    engine_init();
    notation_row_count = 0;
    memset(notation_moves, 0, sizeof(notation_moves));
    memset(notation_players, 0, sizeof(notation_players));

    PackGame(&rec);
    chk("fresh game packs to a valid record", SaveDataOK(&rec), 1);

    memcpy(board_snap, board, sizeof(board_snap));
    side_before = side; rights_before = castle_rights;
    ep_before = ep_square; state_before = engine_state;

    memset(board, 0, sizeof(board));
    side = CBLACK; castle_rights = 0; ep_square = 99; engine_state = 3;

    RestoreGame(&rec);
    for (i = 0; i < 128; ++i)
        if (board[i] != board_snap[i]) break;
    chk("round trip restores every square", i, 128);
    chk("round trip restores side", side, side_before);
    chk("round trip restores castling rights", castle_rights, rights_before);
    chk("round trip restores en passant target", ep_square, ep_before);
    chk("round trip restores engine state", engine_state, state_before);

    /* --- a game with rights spent and an en passant target ------- */
    engine_init();
    play("e2", "e4"); side = CWHITE;      /* keep driving as white */
    play("g1", "f3"); side = CWHITE;
    play("f1", "c4"); side = CWHITE;
    play("e1", "g1"); side = CWHITE;      /* castles: rights change */
    play("d2", "d4"); side = CWHITE;      /* double push: ep target */

    chk("white has castled, rights withdrawn",
        castle_rights & (CR_WK | CR_WQ), 0);
    chk("double push left an en passant target",
        ep_square >= 0, 1);

    notation_row_count = 3;
    strcpy(notation_moves[0], "e2e4"); notation_players[0] = WHT;
    strcpy(notation_moves[1], "e7e5"); notation_players[1] = BLK;
    strcpy(notation_moves[2], "e1g1"); notation_players[2] = WHT;

    PackGame(&rec);
    chk("mid-game record validates", SaveDataOK(&rec), 1);

    memcpy(board_snap, board, sizeof(board_snap));
    ep_before = ep_square; rights_before = castle_rights;

    engine_init();                        /* wipe everything */
    notation_row_count = 0;
    memset(notation_moves, 0, sizeof(notation_moves));

    RestoreGame(&rec);
    for (i = 0; i < 128; ++i)
        if (board[i] != board_snap[i]) break;
    chk("mid-game board restored", i, 128);
    chk("mid-game rights restored", castle_rights, rights_before);
    chk("mid-game ep target restored", ep_square, ep_before);
    chk("move log count restored", notation_row_count, 3);
    chk("move log entry restored", strcmp(notation_moves[2], "e1g1"), 0);
    chk("move log player restored", notation_players[1], BLK);
    chk("restored position is legal", ChessPositionOK(), 1);

    /* --- the validator rejects damaged records ------------------- */
    PackGame(&rec); rec.magic0 = 'X';
    chk("wrong magic rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.version = 99;
    chk("wrong version rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.squares[0] = 200;
    chk("impossible piece code rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.squares[4] = 0;       /* delete the black king */
    chk("missing king rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.squares[20] = CBLACK | 3;   /* a second one */
    chk("duplicate king rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.squares[30] = CWHITE | 2;   /* white black-pawn */
    chk("pawn of the wrong colour rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.mover = 7;
    chk("bad side to move rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.rights = 0xFF;
    chk("stray castling-rights bits rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.ep = 200;
    chk("out of range ep target rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.log_count = 99;
    chk("impossible log length rejected", SaveDataOK(&rec), 0);

    PackGame(&rec); rec.state = 42;
    chk("impossible engine state rejected", SaveDataOK(&rec), 0);

    PackGame(&rec);
    chk("an untouched record still validates", SaveDataOK(&rec), 1);

    /* --- rights cannot be conjured by editing the file ----------- */
    engine_init();
    PackGame(&rec);
    rec.squares[7] = 0;                 /* remove the h8 rook ... */
    rec.rights = CR_ALL;                /* ... but claim all rights */
    chk("record with a missing rook still structurally valid",
        SaveDataOK(&rec), 1);
    RestoreGame(&rec);
    chk("restore withdraws the unsupported right",
        castle_rights & CR_BK, 0);
    chk("the other rights survive", castle_rights & CR_WK, CR_WK);

    printf("\n%d failure(s)\n", fails);
    return fails != 0;
}
'''

out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "build", "savetest.c")
outdir = os.path.dirname(os.path.abspath(out))
if outdir and not os.path.isdir(outdir):
    os.makedirs(outdir)

with io.open(out, "w", encoding="utf-8") as f:
    f.write(harness)

print("mksavetest: wrote %s (record %d lines, logic %d lines)"
      % (out, record.count("\n"), logic.count("\n")))
