//
//	This file was generated by the GEOS Resource Compiler
//
//	DO NOT EDIT! Any changes will be lost!
//
//	Edit proper resource file instead.
//

void NewGame (void);
void switch4080 (void);
void EnterDeskTop (void);

const void subMenu1 = {
	(char)12, (char)54,
	(int)0, (int)66,
	(char)(3 | VERTICAL),
	"new game", (char)MENU_ACTION, (int)NewGame,
	"switch 40/80", (char)MENU_ACTION, (int)switch4080,
	"quit", (char)MENU_ACTION, (int)EnterDeskTop,
};


const void mainMenu = {
	(char)0, (char)15,
	(int)0, (int)27,
	(char)(1 | HORIZONTAL),
	"geos", (char)SUB_MENU, (int)&subMenu1,
};

